# My Jupyter Notebook on IBM Watson Studio

**My name is Pamanji Jagadesh**
I'm a graduated student, learning Data Science is my prime duty of the entire day.

*I am interested in data science because, i would love to contribute towards affordable and quality helthcare in the future.*

### In the below cell I'm trying to print the name of my native place.

In [1]:
print("Dugaraja Patnam")

Dugaraja Patnam

### Horizontal rule shown below.
***
* this is the example for bulleted list
* This is alson an another example for bulleted list.
***
1. Numbered list.
2. Numbered list.
3. Example for Numbered list.

|Name||Place||Date|
|-||-||-|
|Jagadesh||Dugaraja patnam||28th july, 2022|

[naa anveshana](www.youtube.com/naaanveshana)